version: '3.8'

services:
  n8n-parallels:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - READ_TIMEOUT=30
      - WRITE_TIMEOUT=30
      - SHUTDOWN_TIMEOUT=30
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Optional: Add resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

networks:
  default:
    name: n8n-parallels-network